### ISSUE TITLE
multi_column.py errors with latest version of pymupdf

### ISSUE THREAD

**Issue by egh** [pymupdf/PyMuPDF-Utilities#128]
When running the https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/text-extraction/multi_column.py script with version 1.23.22 of pymupdf, the script errors as follows:
```
$ poetry run python ~/multi_column.py ~/sun2004.pdf 
Traceback (most recent call last):
  File "/home/egh/multi_column.py", line 320, in <module>
    bboxes = column_boxes(page, footer_margin=footer_margin, header_margin=header_margin)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egh/multi_column.py", line 206, in column_boxes
    bbox = fitz.IRect(b["bbox"])  # bbox of the block
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/egh/.cache/pypoetry/virtualenvs/copymatch-bWgclluP-py3.12/lib/python3.12/site-packages/fitz/__init__.py", line 13103, in __init__
    self.x0, self.y0, self.x1, self.y1 = util_make_irect( *args, p0=p0, p1=p1, x0=x0, y0=y0, x1=x1, y1=y1)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/egh/.cache/pypoetry/virtualenvs/copymatch-bWgclluP-py3.12/lib/python3.12/site-packages/fitz/__init__.py", line 20332, in util_make_irect
    a = convert(a)
        ^^^^^^^^^^
  File "/home/egh/.cache/pypoetry/virtualenvs/copymatch-bWgclluP-py3.12/lib/python3.12/site-packages/fitz/__init__.py", line 20330, in convert
    assert ret == x
AssertionError
```

**Comment by JorjMcKie** [comment]
This repository does not accept bug issues for fixing - see the readme file.
Otherwise, this is a known error in the main repo which is going to be fixed.

**Comment by egh** [comment]
Thank you for the update! I appreciate the help

**Comment by maxjeblick** [comment]
Example works again with pymupdf-1.24.4

**Comment by JorjMcKie** [comment]
This script is now part of the new repository https://github.com/pymupdf/RAG, respectively the PyMuPDF-based package [pymupdf4llm](https://pypi.org/project/pymupdf4llm/).

When you use the package's function `to_markdown()`, text is extracted in Markdown format which respects multiple columns and also integrates any tables on the page.
